flask_integrum/main/routes.py
from flask import (render_template, request, Blueprint, jsonify, flash,
                    redirect, url_for)
from flask_login import login_required, current_user
from flask_integrum import db
from flask_integrum.models import Post, Todo
from flask_integrum.posts.forms import PostForm
from bs4 import BeautifulSoup
import requests
from flask_integrum.main.forms import PostAssignment



main = Blueprint("main", __name__)



def fix_row_data(row):
    if row.string is None:
        return "".join([r.string if r.string is not None 
            else "" 
            for r in row.contents]).replace(u"\xa0", "")
    else: 
        return row.string.replace(u"\xa0", "")



@main.route("/schema")
def schema():
    year = request.args.get('resurser', 'p.TGIAA19h')
    url = ('https://schema.mau.se/setup/jsp/Schema.jsp?startDatum=idag'
           '&intervallTyp=m&intervallAntal=6&sprak=SV&sokMedAND=true'
           '&forklaringar=true&resurser={}').format(year)
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")
    schema = soup.select(".schemaTabell .data-grey, .schemaTabell .data-white")
    schema_data = []

    for i, row in enumerate(schema):
        row_data = [child for child in row.children]
        num_cols = len(row_data)
    
        if num_cols == 11:
            
            '''
            Kallar på funktionen fix_row_data() med 
            respektive index(kolumn) från kronox
            '''

            data = {
                "day": fix_row_data(row_data[2]),
                "date": fix_row_data(row_data[3]),
                "time": fix_row_data(row_data[4]),
                "course": fix_row_data(row_data[5]),
                "teacher": fix_row_data(row_data[6]),
                "room": fix_row_data(row_data[7]),
                "resource": fix_row_data(row_data[8]),
                "moment": fix_row_data(row_data[9]),
                "updated": fix_row_data(row_data[10])
            }

            schema_data.append(data)
        else:
            
            data = {
                "day": fix_row_data(row_data[2]),
                "date": fix_row_data(row_data[3]),
                "time": fix_row_data(row_data[4]),
                "course": fix_row_data(row_data[5]),
                "group": fix_row_data(row_data[6]),
                "teacher": fix_row_data(row_data[7]),
                "room": fix_row_data(row_data[8]),
                "resource": fix_row_data(row_data[9]),
                "moment": fix_row_data(row_data[10]),
                "updated": fix_row_data(row_data[11])
            }

            schema_data.append(data)

    return render_template("schema.html", 
                            schema=schema_data, 
                            title="Schema")



@main.route("/hem")
def hem():
    # Sätter sida 1 till default, försöker man ange något annat än en
    # int blir det ValueError.
    page = request.args.get("page", 1, type=int)
    # Hämtar inlägg från databasen och sorterar efter senaste datum
    # paginate ger möjlighet att styra antalet inlägg som visas/sida
    
    posts = Post.query \
                .order_by(Post.date_posted.desc()) \
                .paginate(page=page, per_page=3)
    
    return render_template("index.html", posts=posts)



@main.route("/ia")
def ia():
    url = 'https://edu.mau.se/sv/program/tgiaa'
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")
    utb_data=[]
    utb_plan = soup.select('.edu-plan__term, .edu-plan__description')
    lista=[]

    for i in utb_plan:
        i = i.text
        i = i.strip(' ')
        lista.append(i)

    # Sparar variablerna i ett dict
    data = {
        "Programkod": lista[0],
        "Data1": lista[1],
        "Engelsk_benämning": lista[2],
        "Data2": lista[3],
        "Undervisningsspråk": lista[4],
        "Data3": lista[5],
        "Inrättandedatum": lista[6], 
        "Data4": lista[7],
        "Fastställandedatum": lista[8],
        "Data5": lista[9],
        "Beslutande_instans": lista[10],
        "Data6": lista[11],
        "Gäller_från": lista[12],
        "Data7": lista[13],
        "Ersätter": lista[14],
        "Data8": lista[15],
    }

    utb_data.append(data)
    return render_template("ia.html",
                            tabledata=utb_data, 
                            title="Informationsarkitekt")



@main.route("/calendar")
def calendar():
    return render_template("calendar.html", title="Calendar")



@main.route("/om_oss")
def om_oss():
    return render_template("om_oss.html", title="Om Oss")



@main.route("/kontakt")
def kontakt():
    return render_template("kontakt.html", title="Kontakt")



@main.route("/forum", methods=["GET", "POST"])
def forum():
    form = PostForm()
    
    if form.validate_on_submit():
        post = Post(title=form.title.data, 
                    content=form.content.data, 
                    author=current_user)

        db.session.add(post)
        db.session.commit()
        flash("Ditt inlägg har publicerats!", "success")
        return redirect(url_for("main.forum"))

    '''
    Sätter sida 1 till default, 
    försöker man ange något annat än en int blir det ValueError.
    '''

    page = request.args.get("page", 1, type=int)

    '''
    Hämtar inlägg från databasen och sorterar efter senaste datum, 
    paginate ger oss möjlighet att styra hur många inlägg visas/sida
    '''

    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page,
                                                                per_page=5)
    return render_template("forum.html", 
                            title="Forum",
                            posts=posts,
                            form=form, 
                            legend="Nytt inlägg")



#Lägg till upggiften till "att-göra" listan
@main.route("/add_todo", methods=["POST"])
def add_todo():
    task = PostAssignment()

    if task.validate_on_submit():
        todo = Todo(assignment=task.assignment.data, 
                    description=task.description.data, 
                    completed=False, 
                    user_id=current_user.id)

        db.session.add(todo)
        db.session.commit()
        flash("En ny uppgift har skapats!", "success")
        return redirect(url_for("main.todo"))
    
    return render_template("todo.html", 
                            title="Att göra", 
                            legend="Lägg till ny uppgift", 
                            task=task)



#Ta bort uppgift från "att-göra" listan
@main.route("/delete_todo/<id>")
def delete_todo(id):
    
    '''
    Tar bort uppgiften med id:et man klickat på 
    i "att-göra" listan från databasen
    '''

    todo = Todo.query.filter_by(id=int(id)).first()
    db.session.delete(todo)
    db.session.commit()

    return redirect(url_for("main.todo"))
    


#"Att-göra" listan där man kan lägga till uppgifter som ska göras
@main.route("/todo")
def todo():
    task = PostAssignment()

    '''
    Hämtar ut alla assignments som tillhör current_user,
    alltså kollar att user_id i databasen == current_user
    '''

    assignments = Todo.query.filter(Todo.user_id == current_user.id).all()
    return render_template("todo.html", 
                            title="Att göra", 
                            assignments=assignments, 
                            task=task)



@main.route("/faq")
def faq():
    return render_template("faq.html", title="FAQ")



@main.route("/uppgift")
def uppgift():
    return render_template("uppgift.html", title="Uppgift")

flask_integrum/posts/routes.py
from flask import (render_template, url_for, flash, redirect,
                    request, abort, Blueprint)
from flask_login import current_user, login_required
from flask_integrum import db
from flask_integrum.models import Post
from flask_integrum.posts.forms import PostForm



posts = Blueprint("posts", __name__)



#Varje post får en unik sökväg
@posts.route("/post/<int:post_id>")
def post(post_id):
    #Om sökvägen inte finns, returnera 404
    post = Post.query.get_or_404(post_id)
    return render_template("post.html", 
                            title=post.title, 
                            post=post)



#Uppdatera inlägg
@posts.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    #Om sökvägen inte finns, returnera 404
    post = Post.query.get_or_404(post_id)

    #Om skaparen av inlägget inte är inloggad, raise felmeddelande
    if post.author != current_user:
        abort(403)
    form = PostForm()

    #Om uppdateringen validerar, uppdatera inlägg
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("Inlägget har uppdaterats!", "success")
        return redirect(url_for("posts.post", post_id=post.id))

    elif request.method == "GET":
        #Fyller i fälten med texten som finns i nuläget
        form.title.data = post.title
        form.content.data = post.content
    
    '''
    Sätter sida 1 till default, försöker man ange
    något annat än en int blir det ValueError.
    '''

    page = request.args.get("page", 1, type=int)

    '''
    Hämtar inlägg från databasen och sorterar efter senaste datum.
    Paginate ger oss möjlighet att styra hur många 
    inlägg som ska visas per sida etc.
    '''

    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page,
                                                                 per_page=5)
    return render_template("update_post.html", 
                            title="Update Post",   
                            form=form, 
                            posts=posts, 
                            legend="Uppdatera Inlägg")



#Ta bort inlägg
@posts.route("/post/<int:post_id>/delete", methods=["GET", "POST"])
@login_required
def delete_post(post_id):

    #Om sökvägen inte finns, returnera 404
    post = Post.query.get_or_404(post_id)

    #Om skaparen av inlägget inte är inloggad, raise felmeddelande
    if post.author != current_user:
        abort(403)
        
    #Tar bort inlägget
    db.session.delete(post)
    db.session.commit()
    flash("Ditt inlägg är borttaget!", "success")
    return redirect(url_for("main.forum"))

flask_integrum/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_integrum import db, bcrypt
from flask_integrum.models import User, Post
from flask_integrum.users.forms \
    import (RegistrationForm, LoginForm, UpdateAccountForm,
            RequestResetForm, ResetPasswordForm)
from flask_integrum.users.utils import save_picture, send_reset_email

users = Blueprint("users", __name__)



@users.route("/register", methods=["GET", "POST"])
def register():
    #Om användaren redan är inloggad
    #kommer man inte till inloggningen igen
    if current_user.is_authenticated:
        return redirect(url_for("main.hem"))
    form = RegistrationForm()
    if form.validate_on_submit():
        #Krypterar lösenordet i formuläret, görs om till sträng
        hashed_password = \
                        bcrypt.generate_password_hash \
                        (form.password.data).decode("utf-8")
        user = User(username=form.username.data, 
                    email=form.email.data, 
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash("Konto skapat med användarnamn '{}'" \
            .format(form.username.data), "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", 
                            title="Registrera", 
                            form=form)



#Sidan för att logga in, är även startsidan
@users.route("/")
@users.route("/login", methods=["GET", "POST"])
def login():
    #Om användaren redan är inloggad 
    #kommer man inte till inloggningen igen
    if current_user.is_authenticated:
        return redirect(url_for("main.hem"))
    form = LoginForm()
    if form.validate_on_submit():
        #Kontrollerar att där finns en email i 
        #databasen som stämmer överens med angiven email
        user = User.query.filter_by(email=form.email.data).first()
        #Om emailen finns, kontrollera att 
        #lösenordet i databasen matchar angivet lösenord
        if user and bcrypt.check_password_hash \
        (user.password, form.password.data):
            flash("Du är nu inloggad!", "success")
            #Loggar in användaren,
            #remember är valet om man vill komma ihåg användaren
            login_user(user, remember=form.remember.data)
            #Om man kommer till en sida som kräver inloggning
            #tas man vidare till den sidan 
            #efter inloggning istället för "hem"
            next_page = request.args.get("next")
            return redirect(next_page) \
            if next_page else redirect(url_for("main.hem"))      
        else:
            flash("Inloggningen misslyckades," \
                    "kontrollera email och lösenord!", "danger")
    return render_template("login.html", title="Logga in", form=form)



#Om användaren trycker på logga ut
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("users.login"))



#Profilsidan för varje användare
@users.route("/profil", methods=["GET", "POST"])
@login_required #Måste vara inloggad för att komma åt sin profil
def profil():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            #Om där finns en bild att ladda upp, 
            #Spara ner filen och uppdatera profilbild
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        
        #Om formuläret validerat, ersätt med data från formuläret
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        
        flash("Ditt konto har uppdaterats!", "success")
        return redirect(url_for("users.profil"))
        
    #Fyller i fälten med current användarnamn och email
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    #Default profilbild hämtas från databasen 
    #Om profilbild inte laddas upp av användaren
    image_file = url_for("static", 
                        filename="images/profile_pics/" \
                        + current_user.image_file)

    return render_template("profil.html", 
                            title="Min profil", 
                            image_file=image_file, 
                            form=form)



#Visar alla inlägg en viss användare gjort 
#(När man klickar på användarnamnet på ett inlägg)
@users.route("/user/<string:username>")
def user_posts(username):
    #Sätter sida 1 till default, 
    #Försöker man ange något annat än en int blir det ValueError.
    page = request.args.get("page", 1, type=int)
    #Om användaren inte hittas, returnera en 404-error
    user = User.query.filter_by(username=username).first_or_404()
    #Hämtar inlägg från databasen och sorterar efter senaste datum, 
    #Paginate ger oss möjlighet att styra hur
    #Många inlägg som ska visas per sida etc.
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template("user_posts.html", 
                            posts=posts, 
                            user=user)



#Formuläret om förfrågan att återställa lösenordet,
#Validering av email för att kontrollera att kontot finns
@users.route("/reset_password", methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.hem"))
    form = RequestResetForm()
    if form.validate_on_submit():
        #Om formuläret validerat, 
        #Hämta ut angiven email från databasen och
        #Lagrar i variabeln "user"
        user = User.query.filter_by(email=form.email.data).first()
        #Skicka email till användaren
        send_reset_email(user)
        flash("Ett email har skickats med " \
                "instruktioner för att återställa lösenordet!", "info")
        return redirect(url_for("users.login"))
    return render_template("reset_request.html", 
                            title="Återställ Lösenord", 
                            form=form)



#Formuläret där återställningen av lösenordet faktiskt sker, 
#Anger nytt lösenord
@users.route("/reset_password/<token>", methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.hem"))
    user = User.verify_reset_token(token)
    if user is None:
        #Om user = None, alltså om token är fel eller har utgått 
        #Visa felmeddlenade och returnera sidan
        #För att återställa lösenord
        flash("Återställningsnyckeln är" \
                "felaktig eller har utgått!", "warning")
        return redirect(url_for("users.reset_request"))
    
    form = ResetPasswordForm()
    if form.validate_on_submit():
        #Krypterar lösenordet som skrivs in i formuläret,
        #Görs om till sträng
        hashed_password = bcrypt.generate_password_hash \
                            (form.password.data).decode("utf-8")
        user.password = hashed_password
        db.session.commit()
        flash("Ditt lösenord har uppdaterats!", "success")
        return redirect(url_for("users.login"))
    return render_template("reset_token.html", 
                            title="Återtställ Lösenord", 
                            form=form)

flask_integrum/templates/forum.html
{% extends "layout.html" %}

{% block content %}
    <h1>Studentforum</h1>

    <!-- Om användare är inloggad, visa "Skapa inlägg" och själva forumet-->
    {% if current_user.is_authenticated %}

        <!-- Skapa inlägg -->
        <div class="content-section">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">{{ legend }}</legend>

                    <div class="form-group">
                        {{ form.title.label(class="form-control-label") }}
                        {% if form.title.errors %}
                            {{ form.title(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.title.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.title(class="form-control form-control-lg", placeholder="Titel på inlägg..") }}
                        {% endif %}
                    </div>

                    <div class="form-group">
                        {{ form.content.label(class="form-control-label") }}
                        {% if form.content.errors %}
                            {{ form.content(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.content(class="form-control form-control-lg", placeholder="Text i inlägget..") }}
                        {% endif %}
                    </div>
                </fieldset>

                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>

        {% for post in posts.items %}
            <article class="media forum-content-section">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/profile_pics/' + post.author.image_file) }}">
                <div class="media-body">
                    <div class="article-metadata">
                        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                    </div>
                    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                    <p class="article-content">{{ post.content }}</p>
                </div>

            </article>
        {% endfor %}
        <div class="forum-buttons">
            <!-- Visar sidonummer så man kan bläddra för att se fler inlägg -->
            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=3) %}
                <!-- Om sidonumret finns, gå till sidan-->
                {% if page_num %}
                    <!-- Gör så att knappen för sidan vi är på just nu är helmarkerad tillskillnad från övriga knappar -->
                    {% if posts.page == page_num %}
                        <a class="btn btn-info mb-4" href="{{ url_for('main.forum', page=page_num) }}">{{ page_num }}</a>
                        
                    {% else %}
                        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.forum', page=page_num) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                ...
                {% endif %}
            {% endfor %}
        </div>
    
    <!-- Om användaren inte är inloggad, visa bara forumet och inte "Skapa inlägg"-->
    {% else %}

        {% for post in posts.items %}
            <article class="media forum-content-section">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/profile_pics/' + post.author.image_file) }}">
                <div class="media-body">
                    <div class="article-metadata">
                        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                    </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
                </div>
            </article>
        {% endfor %}

        <div class="forum-buttons">
            <!-- Visar sidonummer så man kan bläddra för att se fler inlägg -->
            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=3) %}
                <!-- Om sidonumret finns, gå till sidan-->
                {% if page_num %}
                    <!-- Gör så att knappen för sidan vi är på just nu är helmarkerad tillskillnad från övriga knappar -->
                    {% if posts.page == page_num %}
                        <a class="btn btn-info mb-4" href="{{ url_for('main.forum', page=page_num) }}">{{ page_num }}</a>
                        
                    {% else %}
                        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.forum', page=page_num) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                ...
                {% endif %}
            {% endfor %}
        </div>
    
    {% endif %}

{% endblock content %}

flask_integrum/templates/layout.html
<!doctype html>
<html lang="sv">

<head>
    <link href="https://fonts.googleapis.com/css?family=Baloo+Chettan+2&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <!-- Bibliotek till hem-logga -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">    
    <!-- CSS -->
    <link href="{{ url_for('static', filename='css/style.css') }}" type="text/css" rel="stylesheet">

    <!--Responsiv-->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Om sidan har en titel, skriv ut den. Annars använd Integrum som titel -->
    {% if title %}
        <title>Integrum - {{ title }} </title>
    {% else %}
        <title>Integrum</title>
    {% endif %}

    {% block head %} {% endblock head %}
</head>
<body>

    <div id="wrapper">

        <header>

        </header>

        <nav>
            <!-- Kollar om användaren är inloggad, isåfall visar den andra menyaval -->
            {% if current_user.is_authenticated %}
                <a href="/hem" id="home"><i class="fa fa-home"></i></a>

                <!-- Dropdown för Program -->
                <div class="dropdown">
                    <button class="dropbtn">Program</button>
                    <div class="dropdown-content">
                        <a href="{{ url_for('main.ia') }}">Informationsarkitekt</a>
                    </div>
                </div>

                <!-- Dropdown för Schema -->
                <div class="dropdown">
                    <button class="dropbtn">Kalender</button>
                    <div class="dropdown-content">
                        <a href="{{ url_for('main.schema') }}">Schema</a>
                        <a href="{{ url_for('main.todo') }}">Att göra</a>
                    </div>
                </div>

                <!-- Dropdown för Kontakt -->
                <div class="dropdown">    
                    <button class="dropbtn">Kontakt</button>
                    <div class="dropdown-content">
                        <a href="{{ url_for('main.om_oss') }}">Om oss</a>
                        <a href="{{ url_for('main.faq') }}">FAQ</a>
                        <a href="{{ url_for('main.kontakt') }}">Kontakt</a>
                        <a href="{{ url_for('main.forum') }}">Forum</a>
                    </div>
                </div>
            
                <a href="{{ url_for('users.profil') }}">Min profil</a>
                <a href="{{ url_for('users.logout') }}">Logga ut</a>
            {% else %}
                <a href="{{ url_for('users.login') }}">Logga in</a>
                <a href="{{ url_for('users.register') }}">Registrera</a>
                <a href="{{ url_for('main.om_oss') }}">Om oss</a>         
                <a href="{{ url_for('main.kontakt') }}">Kontakt</a>
                <a href="{{ url_for('main.forum') }}">Forum</a>
                <a href="{{ url_for('main.faq') }}">FAQ</a>
            {% endif %}

        </nav>

        <main>
            <div class="row">
                <div class="col-md-6">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
            
            {% block content %} {% endblock %}
            
        </main>

        <footer>
            <p>Integrum - Copyright 2020</p>
        </footer>

    </div>

    <!-- Optional JavaScript -->
    <!--Javascript till schemat-->  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.5.1/moment.min.js"></script> 
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
    <!-- Markerar aktuell sida/knapp i naven -->
    <script type="text/javascript">
        const currentLocation = location.href;
        const menuItem = document.querySelectorAll("a");
        const menuLength = menuItem.length
        for (let i = 0; i<menuLength; i++){
            if(menuItem[i].href === currentLocation){
                menuItem[i].className = "active"
            }
        }
    </script>

</body>
</html>

flask_integrum/templates/post.html
{% extends "layout.html" %}

{% block content %}
    <!-- 
        Sidan för respektive post där man kan uppdatera eller ta bort sitt inlägg
        Varje post visar profilbild, användarnamn och datum inlägget gjordes
    -->
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                {% if post.author == current_user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Uppdatera</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Ta bort</button>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    <!-- Modal som dyker upp för att bekräfta borttag av inlägg -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Vill du verkligen ta bort ditt inlägg?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Stäng</button>
                    <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Ta bort">
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}